### PR TITLE
Update weatherflowudp.py

### PR DESCRIPTION
**Pull request by scottshaffer**
I happen to have 2 stations in the WeatherFlow system because one failed and it was replaced under warranty.  I'm not 100% sure this is the right way to fix it, but the code assumes any HTTP return except 200 is a failure, but in my case trying to pull data from the old station that is no longer in service returns a 500 error.  By breaking out of the while loop looking for observations on that error, it lets the code look at and find data from the second (good) station.

### CODE REVIEW

**Comment by MrPeteH** [comment]
This patch is _also_ crucial because:

- the REST API now returns a list of all station-connected devices, including the WiFi Hub (type "HB")
- but the REST API has no support for type HB observations, returning a 500 server error!

This problem broke my Weewx beginning in mid-December.

I suppose it might be better to check for an HB-type device and not even attempt to access its data... but this patch seems to do the trick just as well. :-D

**Review by MrPeteH — APPROVED** [review]
Other than a major typo, this is a crucial change and should be quickly merged.

TYPO: on invalid return, it should `continue` the loop, not `break`.

There's been a change to the REST server such that the type HB device incorporated into every Tempest station is:

- Returned as a valid device in the station list
- Is invalid in observation requests, generating a type 500 server error

Thus, my weewx implementation started crashing continually on Dec 23, until this (corrected) patch was incorporated.

**Review by MrPeteH — CHANGES_REQUESTED** [review]
please change from 
                    if (response.status_code == 500): break
to
                    if (response.status_code == 500): continue

(using break causes the normal case to fail: HB device is listed first now in station devices, but fails on observation retrieval. The loop must continue, to obtain the actual station observations ;) )

**Comment by scottshaffer** [comment]
Hmmm - I'm not saying you are wrong, but here was my thinking.  I used break in order to exit the **while** _observation_count_ loop and try the next device - making the assumption (dangerous!) that 500 is the return code when you attempt to make a call for observations from an invalid device (HB, ST, or otherwise).  I expect that means there are no observations to enumerate.  If the code uses continue, I worry it would get stuck in an infinite loop since observation_count should continue to be None?  

All that said, I assume break is working for me but not for you?  And that continue is working for you?

Do we know if WeatherFlow documents that API somewhere?

This code is starting to make me itch a little.  I think it probably really needs to only attempt to read observations from ST device types - sound right?  That would mean checking the type before even entering that while observations_count loop.

**Comment by scottshaffer** [comment]
Thinking about this more, I think 2 changes are needed.  

First, I think readDataFromWF needs to handle 500 errors from the REST API.  500 is not a total failure and shouldn't cause the drive to stop.  This is especially true if the system has more than one station.

Second, I think getStationDevices needs to be modified to only add ST devices to the device_dict.  This skips HB devices and avoids trying to get data from them at all which is less taxing on the API service.  And, since the current code is only designed to work with ST devices, this is safest.  If there are new device types in the future, the code should be modified explicitly to indicate it was tested with those device and add them to the list of supported device types.

**Comment by jjvdgeer** [comment]
I have made my own patch for the problem @MrPeteH mentions. I don't know the effect of my fix on the original problem @scottshaffer encountered though. But you could probably avoid it by defining 'devices' in the weewx.conf file containing the devices that do work.

Anyway, a 500-error means "server error" so if this is returned the WeatherFlow service is failing in some way. A better approach might be to take it up with them.

**Comment by MrPeteH** [comment]
> Anyway, a 500-error means "server error" so if this is returned the WeatherFlow service is failing in some way. A better approach might be to take it up with them.

I did ask. Their response: the API never suggests that non-ST devices can be queried for observations. HB devices can only be queried through the local UDP data stream.

So, I fully agree with Scott's revised approach. Haven't tested the new code yet but will when I get a few round tuits.

**Comment by MrPeteH** [comment]
> Second, I think getStationDevices needs to be modified to only add ST devices to the device_dict. This skips HB devices and avoids trying to get data from them at all which is less taxing on the API service...

@scottshaffer , you know this code WAY better than I do. My only caution is this: the HB device does have attribute data reported locally via the UDP broadcast. _Is there any problem with the HB device going missing in device_dict with respect to incoming UDP data?_

**Comment by scottshaffer** [comment]
The code I changed in getStationDevices limits ST devices to the list of devices to be queried for observations.  I did it very simply for immediate clarity.  It feels OK because I'm worried that new device types (AR or whatever) might not handle observations the same way.  Weatherflow's response to MrPeteH's comment seems to suggest that.  They expect the observations API to work for ST only.

And just for fun, my "old problem" went away - the old failed device that didn't have observations anymore stopped showing up in the device response list.  Of course I see the HB device.

**Comment by MrPeteH** [comment]
@scottshaffer ponders three things:

> If the code uses continue, I worry it would get stuck in an infinite loop since observation_count should continue to be None?
> All that said, I assume break is working for me but not for you? And that continue is working for you?
> Do we know if WeatherFlow documents that API somewhere?

- Shouldn't be an infinite loop. The loop is based on devices, not observation counts.
- `break` definitely broke it ;), because the HB device came before the ST device... so it never saw the ST due to the `break`. And yes, `continue` fixes it for me.
- Yep, the API is more or less documented. [See here](https://weatherflow.github.io/Tempest/api/swagger/#!/observations/getObservationsByDeviceId) (The API 'tree' begins [here](https://weatherflow.github.io/Tempest/api/), with links not only to the REST API, but also the local UDP API (and WebSock)

**Comment by jjvdgeer** [comment]
Continue is the correct approach. The reason it loops through all the devices is that weewx can only receive observations for one timestamp once, you cannot modify it. So it loops through all devices, gathers all observations, groups them by timestamp and then submits them.

Breaking out of the loop will break things, and continue is the correct thing to do.

That said, I still much prefer my approach to the one suggested here. My modification asks the type for each device and if it is a hub it skips it. So it is no longer assuming that a hub is called "HB-<something>".

Regarding the 500-error, take a look at the wikipedia page for [HTTP codes](https://en.wikipedia.org/wiki/List_of_HTTP_status_codes): 

> 5xx server error – the server failed to fulfil an _**apparently valid**_ request

(my emphasis)

Whatever you make of it, the request was valid, the server shouldn't have failed, and earlier it didn't. No, the hub doesn't provide observations, so it should return an empty collection, not a 500-error. Or if that would be something that is not supported, then maybe 400 Bad Request or something. 500 is a server error, so the problem is not at the client (ie. the driver).

**Comment by scottshaffer** [comment]
Works for me.

**Comment by edi-x** [comment]
@scottshaffer, sorry! I missed your pull request. Thank you for reporting this issue.
Also thanks to @MrPeteH and @jjvdgeer for your inputs. I have merged the solution of @jjvdgeer with todays [commit](https://github.com/edi-x/weatherflow-udp/commit/f897442ed218a8944ced691428a3bf178f7dd24c) because it seems to be a more suitable solution.

**Pull request closed without merging**
